name: Deploy Node.js App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to DigitalOcean via SSH
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Navigate to the app directory
            cd BESTRACT || exit

            # Pull the latest changes from the GitHub repository
            git pull origin main

            # Install dependencies
            npm install

            # Restart the app using PM2
            pm2 restart bestract || pm2 start app.js --name bestract

            # Save the PM2 process list
            pm2 save
